const data = {
    products:[
        {
            id:'1',
            name: 'Free Shirt',
            category: 'Shirt',
            image: '/images/shirt6.jpg',
            price: 700,
            brand: 'Nike jdjs',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "Men cool shirt ",
        },
        {
            id: '2',
            name: 'Free Shirt',
            category: 'Shirt',
            image: '/images/shirt7.jpg',
            price: 230,
            brand: 'Nike masdn',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "Men cool shirt ",
        },
        {
            id: '3',
            name: 'Free Shirt mms',
            category: 'Shirt',
            image: '/images/shirt3.webp',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "Men cool shirt ",
        },
        {
            id: '4',
            name: 'Free Shirt',
            category: 'Shirt',
            image: '/images/shirt4.webp',
            price: 230,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "Men cool shirt ",
        },
        {
            id: '5',
            name: 'Free Shirt sdjnsdn  ',
            category: 'Shirt',
            image: '/images/shirt5.webp',
            price: 560,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "Men cool shirt ",
        },
    ]
}

export default data;