import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import { Button, Card, CardActionArea, CardActions, CardContent, CardMedia, Grid, Typography } from '@material-ui/core'
import data from '../utils/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Commerces</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Layout>
        <h1>
          Products
        </h1>
        <Grid container spacing={4}>
          {data.products.map((product) => (
            <Grid item md={4} key={product.id}>
              <Card>
                  <CardActionArea>
                       <CardMedia component="img" image={product.image} title={product.name}></CardMedia>
                       <CardContent>
                          <Typography>
                             {product.name}
                          </Typography>
                        </CardContent>  
                  </CardActionArea> 
                  <CardActions>
                    <Typography>Rs {product.price}</Typography>
                    <Button size="small" color="primary">Add to Cart</Button>
                  </CardActions>
                   
              </Card> 
            </Grid> 
          ))}
        </Grid>
    </Layout>
     
       
    </div>
  )
}


